# Application Configuration
browser=chrome
url=https://www.makemytrip.com/flights/
implicitWait=10
explicitWait=20
headless=false

# Search Defaults
sourceCity=Delhi
destinationCity=Mumbai
daysFromTodayInNextMonth=30
googleUrl=https://www.google.com
googleSearchQuery=MakeMyTrip flight status
